name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # 时间线
          SHOW_LINES_OF_CODE: TRUE
          SHOW_TOTAL_CODE_TIME: TRUE
          SHOW_PROFILE_VIEWS: TRUE
          SHOW_LOC_CHART: TRUE
          SHOW_PROJECTS: FALSE
          SHOW_LANGUAGE_PER_REPO: TRUE
          SHOW_SHORT_INFO: FALSE
          SYMBOL_VERSION: 3
